name: 'SLSA Build Provenance Action'
description: 'An action to generate SLSA build provenance for an artifact'
branding:
  icon: lock
  color: purple
inputs:
  artifact_path:
    description: 'path to artifact or directory of artifacts'
    required: true
  output_path:
    description: 'path to write build provenance file'
    required: true
    default: 'build.provenance'
  github_context:
    description: 'internal (do not set): the "github" context object in json'
    required: true
    default: ${{ toJSON(github) }}
  runner_context:
    description: 'internal (do not set): the "runner" context object in json'
    required: true
    default: ${{ toJSON(runner) }}
  tag_name:
    description: |
      The github release to generate provenance on.
      (if set the artifacts will be downloaded from the release and the provenance will be added as an additional release asset.)
    required: false
runs:
  using: 'docker'
  image: 'docker://philipssoftware/slsa-provenance:v0.2.0-rc1'
  args:
    - "generate"
    - "-artifact_path"
    - '${{ inputs.artifact_path }}'
    - "-output_path"
    - '${{ inputs.output_path }}'
    - "-github_context"
    - '${{ inputs.github_context }}'
    - "-runner_context"
    - '${{ inputs.runner_context }}'
    - "-tag_name"
    - '${{ inputs.tag_name }}'
